### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by faizilham** [haritsE/pokegram#1]
serem serem
sembah2

**Comment by haritsE** [comment]
belum kelar tapi wkwkwkw
cobain iz di @PokeGramBot

2015-07-30 16:34 GMT+07:00 Faiz Ilham notifications@github.com:

> serem serem
> sembah2
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/haritsE/pokegram/issues/1.

## 

Muhammad _Harits_ Shalahuddin Adil Haqqi Elfahmi
16511190/13511046
Divisi Intrakampus HMIF ITB
Teknik Informatika ITB 2011
